// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

interface IERC20S {
    function transfer(address to, uint256 amount) external returns (bool);
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
}

/// @notice ERC-4626-style staking vault: holders deposit the AgentToken (the asset) and earn
///         **USDC** yield (Synthetix reward-per-share accumulator) generated by the agent's revenue.
/// @dev shares are 1:1 with the asset (the asset does not accrue in-kind). USDC rewards are separate.
contract AgentStakingVault {
    IERC20S public immutable asset; // AgentToken (deposited)
    IERC20S public immutable usdc; // rewards

    string public name;
    string public symbol;
    uint8 public constant decimals = 18;

    uint256 public totalSupply;
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    uint256 public accRewardPerShare; // scaled 1e18
    mapping(address => uint256) public rewardDebt;
    uint256 public pool; // USDC held but not yet allocated (no shares yet)

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event Deposit(address indexed caller, address indexed owner, uint256 assets, uint256 shares);
    event Withdraw(address indexed caller, address indexed receiver, address indexed owner, uint256 assets, uint256 shares);
    event RewardNotified(uint256 amount);
    event Claimed(address indexed user, uint256 amount);

    error ZeroAmount();
    error NotAllowed();
    error TransferFailed();

    constructor(address asset_, address usdc_, string memory name_, string memory symbol_) {
        asset = IERC20S(asset_);
        usdc = IERC20S(usdc_);
        name = name_;
        symbol = symbol_;
    }

    //  ---- ERC-4626-ish views (1:1) ----

    function totalAssets() public view returns (uint256) {
        return totalSupply;
    }
    function convertToShares(uint256 assets) public pure returns (uint256) {
        return assets;
    }
    function convertToAssets(uint256 shares) public pure returns (uint256) {
        return shares;
    }
    function previewDeposit(uint256 assets) public pure returns (uint256) {
        return assets;
    }
    function previewWithdraw(uint256 assets) public pure returns (uint256) {
        return assets;
    }
    function previewRedeem(uint256 shares) public pure returns (uint256) {
        return shares;
    }

    //  ---- ERC-20-like share accounting ----

    function approve(address spender, uint256 amount) external returns (bool) {
        allowance[msg.sender][spender] = amount;
        emit Approval(msg.sender, spender, amount);
        return true;
    }

    //  ---- ERC-4626 core ----

    function deposit(uint256 assets, address receiver) external returns (uint256 shares) {
        if (assets == 0) revert ZeroAmount();
        shares = assets;
        if (!asset.transferFrom(msg.sender, address(this), assets)) revert TransferFailed();

        rewardDebt[receiver] += (shares * accRewardPerShare) / 1e18;
        balanceOf[receiver] += shares;
        totalSupply += shares;

        if (pool > 0) {
            accRewardPerShare += (pool * 1e18) / totalSupply;
            pool = 0;
            //  do NOT re-sync rewardDebt: the receiver accrues the held rewards.
        }

        emit Transfer(address(0), receiver, shares);
        emit Deposit(msg.sender, receiver, assets, shares);
    }

    function _withdraw(uint256 shares, address receiver, address owner_) internal returns (uint256 assets) {
        if (shares == 0) revert ZeroAmount();
        if (msg.sender != owner_) {
            uint256 a = allowance[owner_][msg.sender];
            if (a < shares) revert NotAllowed();
            if (a != type(uint256).max) allowance[owner_][msg.sender] = a - shares;
        }
        assets = shares;

        uint256 p = pendingRewards(owner_);
        rewardDebt[owner_] = (balanceOf[owner_] * accRewardPerShare) / 1e18;
        balanceOf[owner_] -= shares;
        totalSupply -= shares;
        rewardDebt[owner_] -= (shares * accRewardPerShare) / 1e18;

        if (p > 0 && !usdc.transfer(receiver, p)) revert TransferFailed();
        if (!asset.transfer(receiver, assets)) revert TransferFailed();

        emit Transfer(owner_, address(0), shares);
        emit Withdraw(msg.sender, receiver, owner_, assets, shares);
    }

    function withdraw(uint256 assets, address receiver, address owner_) external returns (uint256 shares) {
        return _withdraw(assets, receiver, owner_);
    }

    function redeem(uint256 shares, address receiver, address owner_) external returns (uint256 assets) {
        return _withdraw(shares, receiver, owner_);
    }

    //  ---- rewards (USDC) ----

    function pendingRewards(address user) public view returns (uint256) {
        return (balanceOf[user] * accRewardPerShare) / 1e18 - rewardDebt[user];
    }

    /// @notice Injects USDC yield. If there are no stakers yet, it is held in `pool` for the next depositor.
    function notifyReward(uint256 amount) external {
        if (amount == 0) revert ZeroAmount();
        if (!usdc.transferFrom(msg.sender, address(this), amount)) revert TransferFailed();
        if (totalSupply == 0) {
            pool += amount;
        } else {
            accRewardPerShare += (amount * 1e18) / totalSupply;
        }
        emit RewardNotified(amount);
    }

    function claim() external returns (uint256 p) {
        p = pendingRewards(msg.sender);
        rewardDebt[msg.sender] = (balanceOf[msg.sender] * accRewardPerShare) / 1e18;
        if (p > 0) {
            if (!usdc.transfer(msg.sender, p)) revert TransferFailed();
            emit Claimed(msg.sender, p);
        }
    }
}
